### ISSUE TITLE
scriptrails patch calls non-existent script

### ISSUE THREAD

**Issue by nate2014jatc** [Project-Rails/ProjectRails#1]
When running `scriptrails patch` I get the following error;

`./scriptrails: line 41: scripts/build.sh: No such file or directory`

I've checked the source material, and the file isn't present there either.

**Comment by pisaiah** [comment]
Fixed in https://github.com/Project-Rails/ProjectRails/commit/9b71bde3c72f97e9687a2079a3a77f69a197bf22

**Comment by nate2014jatc** [comment]
Why isn't it fixed in the master?

**Comment by nate2014jatc** [comment]
Edit;
Nevermind.

Nice nijna commit XD
